# .github/workflows/build.yml
name: Build Windows Executable

on:
  release:
    types: [published]

permissions:
  contents: write   # ensure the workflow can upload release assets

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dependency-installs/requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable with PyInstaller
        # --onefile creates a single standalone exe in dist/
        run: pyinstaller --onefile vanity.py

      # Optional: create a ZIP as well (uncomment if you want both)
      # - name: Package executable into ZIP
      #   shell: powershell
      #   run: |
      #     Compress-Archive -Path dist/vanity.exe -DestinationPath vanity.zip

      - name: Upload EXE to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/vanity.exe
          asset_name: vanity.exe
          asset_content_type: application/octet-stream
