name: Build Vanity EXE (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          }
          # manually install known deps
          pip install pyinstaller pynacl mnemonic cryptography rich base58

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --console `
            --add-data "config;config" `
            vanity.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vanity-windows-exe
          path: dist/vanity.exe
